### ISSUE TITLE
Text becoming increasingly mangled on state change

### ISSUE THREAD

**Issue by M-Gomez** [MichaelMilstead/react-conversational-text#1]
When interacting with pretty much anything that changes state the text becomes increasingly more and more garbled and longer. I'd assume it's trying to print multiple lines of conversational text at the same time in the same component or something. The text is defined statically as strings inside the ConversationalText component, so this shouldn't be on my end as far as I'm aware.
![image](https://github.com/MichaelMilstead/react-conversational-text/assets/15865194/cbde67c7-0e2f-4d9e-a455-aba512481167)
After causing several state changes
![image](https://github.com/MichaelMilstead/react-conversational-text/assets/15865194/9a79ddbb-c180-4455-abbb-bd9cd571456b)

**Comment by MichaelMilstead** [comment]
Yep, was able to reproduce, looking into it. Thanks!

**Comment by MichaelMilstead** [comment]
Alright, think I found a fix. Do you mind running `npm i react-conversational-text@beta` and letting me know if that fixes it? @M-Gomez

**Comment by M-Gomez** [comment]
Wow! What a speedy fix, works great, thanks!
